name: Installer Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  version:
    name: Get next version number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.next_version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate version number
        id: next_version 
        uses: ./.github/actions/version

  installer:
    uses: ./.github/workflows/workflow_installer.yml
    needs: version
    permissions:
      actions: write # for uploading artifacts
    with:
      version: ${{ needs.version.outputs.version }}
