on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  installer:
    name: build installer + upload as artifact (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, windows-2019, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ${{ matrix.os }}

      - name: Build installer
        run: make version=${{ inputs.version }} installer

      # as long as we do not have a mac m1 runner
      # we have to cross compile
      - name: Build darwin/arm64 installer (cross compilation)
        if: contains(matrix.os, 'mac')
        run: make version=${{ inputs.version }} installer/darwin-arm64

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: cifuzz_installer
          path: build/bin/cifuzz_installer_*
          if-no-files-found: error
          retention-days: 5
